- project:
    name: openstack/vitrage-tempest-plugin
    check:
      jobs:
        - vitrage-dsvm-api-py27
        - vitrage-dsvm-datasources-py27
        - vitrage-dsvm-api-py35
        - vitrage-dsvm-datasources-py35
    gate:
      jobs:
        - vitrage-dsvm-api-py27
        - vitrage-dsvm-datasources-py27
        - vitrage-dsvm-api-py35
        - vitrage-dsvm-datasources-py35